### ISSUE TITLE
BUG-LOAD DATA with fractions

### ISSUE THREAD

**Issue by deathbysora** [deathbysora/anonymous-axolotl#1]
# Problem

MySQL interprets `3/4` as `4` when using Load Data. I've also tried enclosing the fractions with `"` but that didn't seem to work either.

### Example Source File

```
n
3/4
1/2
```

### Output

![load-data-bug-example](https://user-images.githubusercontent.com/100551718/222039623-678a251c-445f-42d5-b402-dd70c0e9ff4e.png)

**Comment by danielyhbi** [comment]
As we discussed last night, the temp workaround would be hardcode the score limit for each attribute. Since `load data` corrected grabbed the numerator (but not the denominator).

If we have time, we can implement a more permanent solution.
