### ISSUE TITLE
Review PM3

### ISSUE THREAD

**Issue by danielyhbi** [deathbysora/anonymous-axolotl#3]
PM3 assignment:
[https://github.com/deathbysora/anonymous-axolotl/blob/2baff43ba3135f82da72cc504414aadb36b92f64/Deliverables/PM3/PM3_draft_danielBi.sql](url)

@Elsa please finish problem #6

@deathbysora please review the whole thing, especially #3 since we got 1000s review from one user after we run the statement

**Comment by deathbysora** [comment]
I opened a pull request for you to review.
